name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Package with jpackage
        run: |
          jpackage --type app-image --name "Fabric Loader" --input build/libs --main-jar trollmod-1.0.0.jar --main-class com.soez.fake.FakeFabricLoader --icon fabric.ico --dest dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fabric-Loader-EXE
          path: dist/
